# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://michaelpginn.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Michael Ginn"
description: Personal website for Michael Ginn, PhD student and software developer

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Michael Ginn
author-bio: Ph.D. Student in Computational Linguistics & NLP  # change to false to hide
author-image: headshot.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin

# use false to turn off any social media links
twitter: https://twitter.com/_michaelginn
facebook: false
instagram: false
github: https://github.com/michaelpginn
linkedin: https://linkedin.com/ginn-michael
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: false

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
